name: Docker Build and Push

on:
  push:
    branches:
      - main  # Menentukan bahwa workflow ini berjalan ketika ada push ke branch main
  pull_request:
    branches:
      - main  # Menentukan bahwa workflow ini berjalan ketika ada pull request ke branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan pekerjaan di VM berbasis Ubuntu

    steps:
      # Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login ke Docker Hub (jika ingin push image ke Docker Hub)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Username Docker Hub, disimpan di GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Password Docker Hub, disimpan di GitHub Secrets

      # Build image Docker
      - name: Build Docker image
        run: |
          docker build -t my-flask-app:latest .

      # Push Docker image ke Docker Hub (optional)
      - name: Push Docker image
        run: |
          docker push my-flask-app:latest
        if: success()  # Push hanya jika build berhasil
